[book]
authors = ["Tony Riemer <driemworks@idealabs.network>"]
language = "en"
multilingual = false
src = "src"
title = "etf-docs"

[output.html]
mathjax-support = true
curly-quotes = true
copy-fonts = true
additional-css = ["custom.css"]
